build:
  nodes:
    analysis:
      environment:
        php:
          version: '7.1.12'
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      environment:
        php:
          version: '7.1.12'
          ini:
            'xdebug.mode': 'coverage'
      dependencies:
        before:
          - sudo apt install -y librabbitmq-dev
          - sudo /home/scrutinizer/.phpenv/versions/7.1.12/bin/pecl channel-update pecl.php.net
          - sudo /home/scrutinizer/.phpenv/versions/7.1.12/bin/pecl install amqp
      tests:
        override:
          - command: php vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
