build:
  nodes:
    analysis:
      environment:
        php:
          version: '7.1'
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      environment:
        php:
          version: '7.1'
          pecl_extensions:
            - amqp
          ini:
            'xdebug.mode': 'coverage'
      dependencies:
        before:
          - sudo apt install -y librabbitmq-dev
      tests:
        override:
          - command: php vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
